### ISSUE TITLE
Old documentations are inaccessible

### ISSUE THREAD

**Issue by ashtum** [boostorg/website-v2#1798]
For example, the following link works correctly on the old website:
https://original.boost.org/doc/libs/1_63_0/doc/html/boost_asio/reference.html
But it does not work on the new site:
https://www.boost.org/doc/libs/1_63_0/doc/html/boost_asio/reference.html

Access to older versions of documentation is essential for users who are working with legacy versions of a library, especially when the library has changed significantly over time.

**Comment by rbbeeston** [comment]
@sdarwin can you take a look at this as well, May be something weird on the server. seems kinda intermittent

**Comment by ashtum** [comment]
> [@ashtum](https://github.com/ashtum) can you confirm what you mean by
> 
> > it does not work on the new site
> 
> I am seeing a 503 timeout that Rob is referring to above. Want to make sure that's the same thing you're referring to.

Yes, that's what I'm seeing on my end too.

**Comment by sdarwin** [comment]
- The CDN might have been caching the 503s.  I have now set the TTL of 503 to 10 mins.
- reference.html is 10MB in size.  May be triggering timeouts in the load balancer. Checking.

**Comment by sdarwin** [comment]
I have applied the following so the Load Balancer timeout is increased from 30 seconds to 120 seconds:

```
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: boost-backend-policy
spec:
  default:
    timeoutSec: 120
  targetRef:
    group: ""
    kind: Service
    name: boost-gateway-svc
```

Next, it appears Django is timing out after 30 seconds when retrieving `/doc/libs/1_63_0/doc/html/boost_asio/reference.html` which is around 10MB in size. 

@GregKaleka , could you replicate this problem locally?  And increase boto's timeout from 30 seconds to 120 seconds?
